### ISSUE TITLE
searchEthLogs not working for hyperspace

### ISSUE THREAD

**Issue by JulianToledano** [Zondax/fil-parser#8]
## Summary

Method `searchEthLogs` is not working for hyperspace. 
https://github.com/Zondax/fil-parser/blob/11f236e4309a2325c69d32f070f5ce3dc3eed217/parser/evm.go#L43-L51
The logs of hyperspace have the following format:
```
data string
topics []string
transactionIndex string
transactionHash string
address string
removed bool
logIndex string
blockHash string
blockNumber string
```
The field `transactionCid` used by searchEthLogs is not longer present so the condition is never fulfilled. I think the address is what should be used but a conversion is needed. Either from fil -> eth or the other way.
[Reference to ethlog](https://github.com/filecoin-project/lotus/blob/v1.20.0/chain/types/ethtypes/eth_types.go#L656-L688)

**Comment by raynaudoe** [comment]
Fixed in #10
